### ISSUE TITLE
Install Cytoscape desktop to load and test CX2 networks

### ISSUE THREAD

**Issue by dexterpratt** [ndexbio/gsoc_llm#18]
Load the CX2 networks to Cytoscape 
Try uploading networks to NDEx from Cytoscape (This assumes that you have created your NDEx account as part of the other issues)
Extra credit: learn how to use Cytoscape features to apply graphic styles and a layout to the network

**Comment by Favourj-bit** [comment]
""" You can use File -> Import -> Network from File … and choose the cx2 file to open it in Cytoscape. or just drag a 
cx2 file from your Finder window to the session pane of your Cytoscape instance. To open it in Cytoscape Web you can 
use Data -> Import -> Network from File and choose a cx2 file from the file chooser. To Upload to NDEx, you have to use 
curl or postman to either post the Json content in the payload to https://www.ndexbio.org/v3/networks , or upload the 
file to that endpoint (it will be the multipart form data format on field “CXNetworkStream”)."""
