### ISSUE TITLE
Provide a diagnosis of the CX2 output problem

### ISSUE THREAD

**Issue by dexterpratt** [ndexbio/gsoc_llm#19]
Dexter will work with the Ideker Lab software team to diagnose the problem and give feedback on the CX2 generation method

**Comment by dexterpratt** [comment]
Jing's response:

[@dexter](https://cytoscape.slack.com/team/U0BPP68F7)
, this is not a valid cx2 file. There are many problems in this file.  It is missing the cx2 descriptor, attributeDeclaration, and status aspects. Looks like it is trying to generate a cx1 file. The file extension is .json. Cytoscape will trying to load it as a CytoscapeJS object I think.

And here is the documentation for CX2 in the ndex2 package:

https://ndex2.readthedocs.io/en/latest/cx2.html

It provides examples of using a CX2Network object to build CX2 networks.

Here is the documentation for generating CX2 json from the object and then saving the CX2 to NDEx:

https://ndex2.readthedocs.io/en/latest/cx2.html#ndex2.cx2.CX2Network.to_cx2
https://ndex2.readthedocs.io/en/latest/ndex2client.html#ndex2.client.Ndex2.save_new_cx2_network

**Comment by Favourj-bit** [comment]
@dexterpratt This is noted
