### ISSUE TITLE
Format to Easily Compare INDRA versus LLM

### ISSUE THREAD

**Issue by cannin** [ndexbio/gsoc_llm#20]
Make a debugging file by making a function

# INPUTS 
1. LLM output JSON
2. INDRA output JSON

# OUTPUTS 
JSON 

{ sentence: "...", llm: ['A RELATION B', 'B RELATION C'], indra: ['C RELATION D', 'B RELATION C'] }

# From Dexter: 
Sentence: “….”
LLM assertions:
A relation B
B relation C
INDRA
A relation B
C relation D
B different relation C

**Comment by Favourj-bit** [comment]
https://github.com/ndexbio/gsoc_llm/blob/main/results/pmc3898398/combined_output.json

Done

@cannin @dexterpratt

**Comment by cannin** [comment]
@Favourj-bit good job. Some of the differences would improve with grounding; I would consider this the next step.

**Comment by Favourj-bit** [comment]
Alright, noted

**Comment by Favourj-bit** [comment]
@cannin @dexterpratt 

I have been able to ground the genes, but I don't know if I can work with the results gotten as it is giving numerical values.
It is in this document: https://github.com/ndexbio/gsoc_llm/blob/main/results/pmc3898398/grounded_llm_combined_results.json

This is also the combined output when i told the llm to convert the genes to the hgnc symbols: https://github.com/ndexbio/gsoc_llm/blob/main/results/pmc3898398/combined_output.json
