### ISSUE TITLE
Set Up Local Code and .env File

### ISSUE THREAD

**Issue by cannin** [ndexbio/gsoc_llm#6]
Put GPT API keys in an .env. Make sure .env file is placed in .gitignore so it is not committed.

https://pypi.org/project/python-dotenv/

**Comment by Favourj-bit** [comment]
Done

**Comment by cannin** [comment]
If using VS Code can you install flake8 extension; you can either leave the default (all checks) or put the flake8 args that I have to ignore certain messages

<img width="1349" alt="Screenshot 2024-05-13 at 11 41 50 AM" src="https://github.com/ndexbio/gsoc_llm/assets/790284/8ff53fec-5b55-4074-83f4-1abb153743fa">

**Comment by Favourj-bit** [comment]
Done
