### ISSUE TITLE
Make Example Code to Extract Get INDRA Interactions for a Publication

### ISSUE THREAD

**Issue by cannin** [ndexbio/gsoc_llm#7]
INDRA currently extracts interactions using various tools. How does GPT-extracted interactions compare? You need to be able to convert either your format to the INDRA format or vice versa. Best to use a format for your summer work that is also compatible with INDRA: https://indra.readthedocs.io/en/latest/modules/assemblers/index.html

Example: https://gist.github.com/cannin/949db7c5a0bbce873704fe90cc58de5a

INDRA accepts either PMC or PMID IDs

https://indra.readthedocs.io/en/latest/_modules/indra/sources/indra_db_rest/api.html

**Comment by Favourj-bit** [comment]
Completed
